allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@aws-sdk/checksums@3.1000.3'
  - '@aws-sdk/client-dynamodb@3.1064.0'
  - '@aws-sdk/client-firehose@3.1064.0'
  - '@aws-sdk/client-s3@3.1064.0'
  - '@aws-sdk/client-sfn@3.1064.0'
  - '@aws-sdk/core@3.974.19'
  - '@aws-sdk/credential-provider-env@3.972.45'
  - '@aws-sdk/credential-provider-http@3.972.47'
  - '@aws-sdk/credential-provider-ini@3.972.51'
  - '@aws-sdk/credential-provider-login@3.972.50'
  - '@aws-sdk/credential-provider-node@3.972.53'
  - '@aws-sdk/credential-provider-process@3.972.45'
  - '@aws-sdk/credential-provider-sso@3.972.50'
  - '@aws-sdk/credential-provider-web-identity@3.972.50'
  - '@aws-sdk/dynamodb-codec@3.973.19'
  - '@aws-sdk/endpoint-cache@3.972.7'
  - '@aws-sdk/lib-dynamodb@3.1064.0'
  - '@aws-sdk/middleware-endpoint-discovery@3.972.18'
  - '@aws-sdk/middleware-flexible-checksums@3.974.28'
  - '@aws-sdk/middleware-sdk-s3@3.972.49'
  - '@aws-sdk/nested-clients@3.997.18'
  - '@aws-sdk/signature-v4-multi-region@3.996.33'
  - '@aws-sdk/token-providers@3.1064.0'
  - '@aws-sdk/types@3.973.12'
  - '@aws-sdk/util-dynamodb@3.996.4'
  - '@aws-sdk/xml-builder@3.972.29'
  - '@tunnelhub/sdk@4.0.0'
  - '@tunnelhub/sdk@4.1.0'
